create table if not exists planning_routes (
    id bigint generated by default as identity primary key,
    planning_date text not null default '',
    source text not null default 'CHESS',
    division text not null default '',
    unit_id text,
    domain text not null default '',
    domain_seq integer not null default 1,
    pdv numeric default 0,
    bultos numeric default 0,
    pure_pallets numeric default 0,
    amount numeric default 0,
    out_route numeric default 0,
    tot_udt numeric default 0,
    tot_dia numeric default 0,
    hectoliters numeric default 0,
    weight numeric default 0,
    picking numeric default 0,
    avg_bultos numeric default 0,
    avg_value numeric default 0,
    avg_hl numeric default 0,
    total_loads numeric default 0,
    comprobantes numeric default 0,
    contact text default '',
    rendicion text default '',
    driver text default '',
    helper1 text default '',
    helper2 text default '',
    locality text default '',
    observations text default '',
    recarga_qty integer default 0,
    status text not null default 'BORRADOR',
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    updated_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    whatsapp_observation text default '',
    kms numeric not null default 0
);

create table if not exists employees (
    id bigint generated by default as identity primary key,
    employee_code text default '',
    name text not null default '',
    division text not null default '',
    primary_role text not null default 'AYUDANTE',
    active integer not null default 1,
    base_locality text default '',
    can_driver integer not null default 0,
    can_helper integer not null default 0
);

create table if not exists vehicle_people (
    id bigint generated by default as identity primary key,
    domain text not null default '',
    employee_name text not null default '',
    role text not null default '',
    priority integer not null default 99,
    active integer not null default 1
);

create table if not exists localities (
    id bigint generated by default as identity primary key,
    name text not null default '',
    division text not null default '',
    sort_order integer not null default 99,
    active integer not null default 1
);

create table if not exists employee_locality_roles (
    id bigint generated by default as identity primary key,
    employee_name text not null default '',
    division text not null default '',
    locality text not null default '',
    can_driver integer not null default 0,
    can_helper integer not null default 0,
    active integer not null default 1
);

create table if not exists personnel_novelties (
    id bigint generated by default as identity primary key,
    novelty_date text not null default '',
    employee_name text not null default '',
    division text not null default '',
    role text not null default '',
    reason text not null default '',
    notes text default '',
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS')
);

create table if not exists recargas (
    id bigint generated by default as identity primary key,
    recarga_date text not null default '',
    route_id bigint,
    employee_name text not null default '',
    role text not null default '',
    quantity integer not null default 1,
    period_start text not null default '',
    period_end text not null default ''
);

create table if not exists mail_log (
    id bigint generated by default as identity primary key,
    mail_date text not null default '',
    planning_date text not null default '',
    recipients text not null default '',
    cc text default '',
    subject text not null default '',
    status text not null default '',
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS')
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    username text not null default '',
    display_name text not null default '',
    password_hash text not null default '',
    role text not null default '',
    assigned_base text not null default 'TODAS',
    active integer not null default 1,
    must_change_password integer not null default 0,
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    updated_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    last_login text default '',
    created_by text default ''
);

create table if not exists user_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint,
    token_hash text not null default '',
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    expires_at text not null default '',
    last_activity text not null default '',
    ip_address text default '',
    user_agent text default '',
    active integer not null default 1
);

create table if not exists audit_log (
    id bigint generated by default as identity primary key,
    user_id bigint,
    username text default '',
    entity_name text not null default 'N/D',
    action text not null default '',
    module text not null default '',
    operational_date text default '',
    division text,
    record_type text default '',
    record_id text default '',
    previous_data text default '',
    new_data text default '',
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    ip_address text default ''
);

alter table planning_routes add column if not exists planning_date text not null default '';
alter table planning_routes add column if not exists source text not null default 'CHESS';
alter table planning_routes add column if not exists division text not null default '';
alter table planning_routes add column if not exists unit_id text;
alter table planning_routes add column if not exists domain text not null default '';
alter table planning_routes add column if not exists domain_seq integer not null default 1;
alter table planning_routes add column if not exists pdv numeric default 0;
alter table planning_routes add column if not exists bultos numeric default 0;
alter table planning_routes add column if not exists pure_pallets numeric default 0;
alter table planning_routes add column if not exists amount numeric default 0;
alter table planning_routes add column if not exists out_route numeric default 0;
alter table planning_routes add column if not exists tot_udt numeric default 0;
alter table planning_routes add column if not exists tot_dia numeric default 0;
alter table planning_routes add column if not exists hectoliters numeric default 0;
alter table planning_routes add column if not exists weight numeric default 0;
alter table planning_routes add column if not exists picking numeric default 0;
alter table planning_routes add column if not exists avg_bultos numeric default 0;
alter table planning_routes add column if not exists avg_value numeric default 0;
alter table planning_routes add column if not exists avg_hl numeric default 0;
alter table planning_routes add column if not exists total_loads numeric default 0;
alter table planning_routes add column if not exists comprobantes numeric default 0;
alter table planning_routes add column if not exists contact text default '';
alter table planning_routes add column if not exists rendicion text default '';
alter table planning_routes add column if not exists driver text default '';
alter table planning_routes add column if not exists helper1 text default '';
alter table planning_routes add column if not exists helper2 text default '';
alter table planning_routes add column if not exists locality text default '';
alter table planning_routes add column if not exists observations text default '';
alter table planning_routes add column if not exists recarga_qty integer default 0;
alter table planning_routes add column if not exists status text not null default 'BORRADOR';
alter table planning_routes add column if not exists created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS');
alter table planning_routes add column if not exists updated_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS');
alter table planning_routes add column if not exists whatsapp_observation text default '';
alter table planning_routes add column if not exists kms numeric not null default 0;

alter table employees add column if not exists employee_code text default '';
alter table employees add column if not exists name text not null default '';
alter table employees add column if not exists division text not null default '';
alter table employees add column if not exists primary_role text not null default 'AYUDANTE';
alter table employees add column if not exists active integer not null default 1;
alter table employees add column if not exists base_locality text default '';
alter table employees add column if not exists can_driver integer not null default 0;
alter table employees add column if not exists can_helper integer not null default 0;

alter table vehicle_people add column if not exists domain text not null default '';
alter table vehicle_people add column if not exists employee_name text not null default '';
alter table vehicle_people add column if not exists role text not null default '';
alter table vehicle_people add column if not exists priority integer not null default 99;
alter table vehicle_people add column if not exists active integer not null default 1;

alter table localities add column if not exists name text not null default '';
alter table localities add column if not exists division text not null default '';
alter table localities add column if not exists sort_order integer not null default 99;
alter table localities add column if not exists active integer not null default 1;

alter table employee_locality_roles add column if not exists employee_name text not null default '';
alter table employee_locality_roles add column if not exists division text not null default '';
alter table employee_locality_roles add column if not exists locality text not null default '';
alter table employee_locality_roles add column if not exists can_driver integer not null default 0;
alter table employee_locality_roles add column if not exists can_helper integer not null default 0;
alter table employee_locality_roles add column if not exists active integer not null default 1;

alter table personnel_novelties add column if not exists novelty_date text not null default '';
alter table personnel_novelties add column if not exists employee_name text not null default '';
alter table personnel_novelties add column if not exists division text not null default '';
alter table personnel_novelties add column if not exists role text not null default '';
alter table personnel_novelties add column if not exists reason text not null default '';
alter table personnel_novelties add column if not exists notes text default '';
alter table personnel_novelties add column if not exists created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS');

alter table recargas add column if not exists recarga_date text not null default '';
alter table recargas add column if not exists route_id bigint;
alter table recargas add column if not exists employee_name text not null default '';
alter table recargas add column if not exists role text not null default '';
alter table recargas add column if not exists quantity integer not null default 1;
alter table recargas add column if not exists period_start text not null default '';
alter table recargas add column if not exists period_end text not null default '';

alter table mail_log add column if not exists mail_date text not null default '';
alter table mail_log add column if not exists planning_date text not null default '';
alter table mail_log add column if not exists recipients text not null default '';
alter table mail_log add column if not exists cc text default '';
alter table mail_log add column if not exists subject text not null default '';
alter table mail_log add column if not exists status text not null default '';
alter table mail_log add column if not exists created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS');

alter table users add column if not exists username text not null default '';
alter table users add column if not exists display_name text not null default '';
alter table users add column if not exists password_hash text not null default '';
alter table users add column if not exists role text not null default '';
alter table users add column if not exists assigned_base text not null default 'TODAS';
alter table users add column if not exists active integer not null default 1;
alter table users add column if not exists must_change_password integer not null default 0;
alter table users add column if not exists created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS');
alter table users add column if not exists updated_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS');
alter table users add column if not exists last_login text default '';
alter table users add column if not exists created_by text default '';

alter table user_sessions add column if not exists user_id bigint;
alter table user_sessions add column if not exists token_hash text not null default '';
alter table user_sessions add column if not exists created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS');
alter table user_sessions add column if not exists expires_at text not null default '';
alter table user_sessions add column if not exists last_activity text not null default '';
alter table user_sessions add column if not exists ip_address text default '';
alter table user_sessions add column if not exists user_agent text default '';
alter table user_sessions add column if not exists active integer not null default 1;

alter table audit_log add column if not exists user_id bigint;
alter table audit_log add column if not exists username text default '';
alter table audit_log add column if not exists entity_name text not null default 'N/D';
alter table audit_log add column if not exists action text not null default '';
alter table audit_log add column if not exists module text not null default '';
alter table audit_log add column if not exists operational_date text default '';
alter table audit_log add column if not exists division text;
alter table audit_log alter column division drop default;
alter table audit_log add column if not exists record_type text default '';
alter table audit_log add column if not exists record_id text default '';
alter table audit_log add column if not exists previous_data text default '';
alter table audit_log add column if not exists new_data text default '';
alter table audit_log add column if not exists created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS');
alter table audit_log add column if not exists ip_address text default '';

create unique index if not exists idx_planning_routes_unique_route
on planning_routes(planning_date, division, domain, domain_seq);
create unique index if not exists idx_employees_name_unique on employees(name);
create unique index if not exists idx_vehicle_people_unique on vehicle_people(domain, employee_name, role);
create unique index if not exists idx_localities_unique on localities(name, division);
create unique index if not exists idx_employee_locality_roles_unique on employee_locality_roles(employee_name, division, locality);
create unique index if not exists idx_personnel_novelties_unique on personnel_novelties(novelty_date, employee_name);
create unique index if not exists idx_recargas_unique on recargas(route_id, employee_name, role);
create unique index if not exists idx_users_username_unique on users(username);
create unique index if not exists idx_user_sessions_token_hash_unique on user_sessions(token_hash);

create index if not exists idx_planning_routes_date_division on planning_routes(planning_date, division);
create index if not exists idx_planning_routes_status on planning_routes(status);
create index if not exists idx_personnel_novelties_date on personnel_novelties(novelty_date);
create index if not exists idx_recargas_date on recargas(recarga_date);
create index if not exists idx_user_sessions_token_hash on user_sessions(token_hash);
create index if not exists idx_user_sessions_active on user_sessions(active,last_activity);
create index if not exists idx_audit_log_created_at on audit_log(created_at);
create index if not exists idx_audit_log_username on audit_log(username);
