create table if not exists planning_routes (
    id bigint generated by default as identity primary key,
    planning_date text not null,
    source text not null default 'CHESS',
    division text not null,
    unit_id text,
    domain text not null,
    domain_seq integer not null default 1,
    pdv numeric default 0,
    bultos numeric default 0,
    pure_pallets numeric default 0,
    amount numeric default 0,
    out_route numeric default 0,
    tot_udt numeric default 0,
    tot_dia numeric default 0,
    hectoliters numeric default 0,
    weight numeric default 0,
    picking numeric default 0,
    avg_bultos numeric default 0,
    avg_value numeric default 0,
    avg_hl numeric default 0,
    total_loads numeric default 0,
    comprobantes numeric default 0,
    contact text default '',
    rendicion text default '',
    driver text default '',
    helper1 text default '',
    helper2 text default '',
    locality text default '',
    observations text default '',
    recarga_qty integer default 0,
    status text not null default 'BORRADOR',
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    updated_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    whatsapp_observation text default '',
    kms numeric not null default 0,
    unique(planning_date, division, domain, domain_seq)
);

create table if not exists employees (
    id bigint generated by default as identity primary key,
    employee_code text default '',
    name text not null unique,
    division text not null,
    primary_role text not null default 'AYUDANTE',
    active integer not null default 1,
    base_locality text default '',
    can_driver integer not null default 0,
    can_helper integer not null default 0
);

create table if not exists vehicle_people (
    id bigint generated by default as identity primary key,
    domain text not null,
    employee_name text not null,
    role text not null,
    priority integer not null default 99,
    active integer not null default 1,
    unique(domain, employee_name, role)
);

create table if not exists localities (
    id bigint generated by default as identity primary key,
    name text not null,
    division text not null,
    sort_order integer not null default 99,
    active integer not null default 1,
    unique(name, division)
);

create table if not exists employee_locality_roles (
    id bigint generated by default as identity primary key,
    employee_name text not null,
    division text not null,
    locality text not null,
    can_driver integer not null default 0,
    can_helper integer not null default 0,
    active integer not null default 1,
    unique(employee_name, division, locality)
);

create table if not exists personnel_novelties (
    id bigint generated by default as identity primary key,
    novelty_date text not null,
    employee_name text not null,
    division text not null,
    role text not null default '',
    reason text not null,
    notes text default '',
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    unique(novelty_date, employee_name)
);

create table if not exists recargas (
    id bigint generated by default as identity primary key,
    recarga_date text not null,
    route_id bigint not null references planning_routes(id) on delete cascade,
    employee_name text not null,
    role text not null,
    quantity integer not null default 1,
    period_start text not null,
    period_end text not null,
    unique(route_id, employee_name, role)
);

create table if not exists mail_log (
    id bigint generated by default as identity primary key,
    mail_date text not null,
    planning_date text not null,
    recipients text not null,
    cc text default '',
    subject text not null,
    status text not null,
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS')
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    display_name text not null,
    password_hash text not null,
    role text not null,
    assigned_base text not null default 'TODAS',
    active integer not null default 1,
    must_change_password integer not null default 0,
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    updated_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    last_login text default '',
    created_by text default ''
);

create table if not exists user_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    token_hash text not null unique,
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    expires_at text not null,
    last_activity text not null,
    ip_address text default '',
    user_agent text default '',
    active integer not null default 1
);

create table if not exists audit_log (
    id bigint generated by default as identity primary key,
    user_id bigint,
    username text default '',
    action text not null,
    module text not null,
    operational_date text default '',
    division text default '',
    record_type text default '',
    record_id text default '',
    previous_data text default '',
    new_data text default '',
    created_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    ip_address text default ''
);

create index if not exists idx_planning_routes_date_division on planning_routes(planning_date, division);
create index if not exists idx_planning_routes_status on planning_routes(status);
create index if not exists idx_personnel_novelties_date on personnel_novelties(novelty_date);
create index if not exists idx_recargas_date on recargas(recarga_date);
create index if not exists idx_user_sessions_token_hash on user_sessions(token_hash);
create index if not exists idx_user_sessions_active on user_sessions(active,last_activity);
create index if not exists idx_audit_log_created_at on audit_log(created_at);
create index if not exists idx_audit_log_username on audit_log(username);
